apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-proxy
  namespace: go-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: savindap/go-proxy
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: go-proxy
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - port: 9000
      targetPort: 9000